// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useState, useEffect } from 'react';
import React_c6c9d5c02e9182eb22f40bc4cf21fc656783d24a from 'react';
import * as React from 'react';
import * as SeparatorPrimitive from '@radix-ui/react-separator';
import { cn } from 'lib/utils';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { XIcon, Sparkles, ChevronDownIcon, Menu, X, Search, Moon, Sun, QuoteIcon, ShoppingCart, AlertCircle, Clock, ArrowLeft, Share2, Download, ExternalLink, ArrowRight, Lightbulb, Calendar, MapPin } from 'lucide-react';
import { Slot } from '@radix-ui/react-slot';
import { cva } from 'class-variance-authority';
import * as AvatarPrimitive from '@radix-ui/react-avatar';
import * as AccordionPrimitive from '@radix-ui/react-accordion';
import componentMap from '.sitecore/component-map';
import { AppPlaceholder, CdpHelper, useSitecore, RichText, Text, DateField, Image as Image_8a80e63291fea86e0744df19113dc44bec187216, Link as Link_8a80e63291fea86e0744df19113dc44bec187216 } from '@sitecore-content-sdk/nextjs';
import Link from 'next/link';
import Image from 'next/image';
import { usePathname } from 'next/navigation';
import { useTheme } from 'next-themes';
import { Button } from 'components/ui/button';
import { getThemeVariant } from 'lib/theme-config';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { Slider } from 'src/components/content/testimonials/list/Testimonials.Slider';
import { Badge } from 'components/ui/badge';
import { Tiles } from 'src/components/content/stats/Stats.Tiles';
import { Button as Button_84330b1bbe8a1bb4486fd11a1e9edfcb73dcb72a } from 'src/components/ui/button';
import { Card, CardContent, CardFooter } from 'src/components/ui/card';
import { Badge as Badge_4993aa9339ae187afc55b9486739db65fa14e5ba } from 'src/components/ui/badge';
import { formatPrice, formatDate } from 'src/lib/data';
import { getFeaturedProducts, formatDate as formatDate_e48efc7333ac73f929d9b272a527b63e4cd08f90, getNextUpcomingEvent } from 'lib/data';
import { ProductCard } from 'src/components/content/products/teaser/_productCard';
import { Tiles as Tiles_49423b085a70264a020b434efb2a0fbe4b23f2fe } from 'src/components/content/products/list/Product.Tiles';
import { Input } from 'src/components/ui/input';
import { getLucideIcon } from 'lib/iconUtils';
import { NewsGrid } from 'src/components/content/news/List/News.Grid';
import client_e836c8c83336161d23b12b70a0f420d5d397b9fe from 'lib/sitecore-client';
import { Default } from 'src/components/content/news/Teaser/NewsCard';
import { Card as Card_ee5df0e436668ea77211f94aa8fc698e82699918, CardContent as CardContent_ee5df0e436668ea77211f94aa8fc698e82699918 } from 'components/ui/card';
import { Separator } from 'src/components/ui/separator';
import { AIGeneratedBadge } from 'components/ui/ai-generated-badge';
import { Default as Default_8df8e6cf104460826f9a1215cfab70bad2ccdef2 } from 'src/components/content/highlight/teaser/HighlightTeaser';
import { Tiles as Tiles_2d2f52aec1ad0fb42654646675f88ac474927af0 } from 'src/components/content/highlight/list/Highlights.Tiles';
import { Slider as Slider_46091ec46945bf6a641b749ef0b0366a3b6b61c0 } from 'src/components/content/brands/Brands.Slider';
import { Separator as Separator_fdcdea374acd645ff8e33dd8c598ebe0a6a71fc0 } from 'components/ui/separator';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React_c6c9d5c02e9182eb22f40bc4cf21fc656783d24a },
      { name: '*', value: React },
    ]
  },
  {
    module: '@radix-ui/react-separator',
    exports: [
      { name: '*', value: SeparatorPrimitive },
    ]
  },
  {
    module: 'lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: '@radix-ui/react-dialog',
    exports: [
      { name: '*', value: DialogPrimitive },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'XIcon', value: XIcon },
      { name: 'Sparkles', value: Sparkles },
      { name: 'ChevronDownIcon', value: ChevronDownIcon },
      { name: 'Menu', value: Menu },
      { name: 'X', value: X },
      { name: 'Search', value: Search },
      { name: 'Moon', value: Moon },
      { name: 'Sun', value: Sun },
      { name: 'QuoteIcon', value: QuoteIcon },
      { name: 'ShoppingCart', value: ShoppingCart },
      { name: 'AlertCircle', value: AlertCircle },
      { name: 'Clock', value: Clock },
      { name: 'ArrowLeft', value: ArrowLeft },
      { name: 'Share2', value: Share2 },
      { name: 'Download', value: Download },
      { name: 'ExternalLink', value: ExternalLink },
      { name: 'ArrowRight', value: ArrowRight },
      { name: 'Lightbulb', value: Lightbulb },
      { name: 'Calendar', value: Calendar },
      { name: 'MapPin', value: MapPin },
    ]
  },
  {
    module: '@radix-ui/react-slot',
    exports: [
      { name: 'Slot', value: Slot },
    ]
  },
  {
    module: 'class-variance-authority',
    exports: [
      { name: 'cva', value: cva },
    ]
  },
  {
    module: '@radix-ui/react-avatar',
    exports: [
      { name: '*', value: AvatarPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-accordion',
    exports: [
      { name: '*', value: AccordionPrimitive },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'useSitecore', value: useSitecore },
      { name: 'RichText', value: RichText },
      { name: 'Text', value: Text },
      { name: 'DateField', value: DateField },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'Link', value: Link_8a80e63291fea86e0744df19113dc44bec187216 },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'usePathname', value: usePathname },
    ]
  },
  {
    module: 'next-themes',
    exports: [
      { name: 'useTheme', value: useTheme },
    ]
  },
  {
    module: 'components/ui/button',
    exports: [
      { name: 'Button', value: Button },
    ]
  },
  {
    module: 'lib/theme-config',
    exports: [
      { name: 'getThemeVariant', value: getThemeVariant },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'src/components/content/testimonials/list/Testimonials.Slider',
    exports: [
      { name: 'Slider', value: Slider },
    ]
  },
  {
    module: 'components/ui/badge',
    exports: [
      { name: 'Badge', value: Badge },
    ]
  },
  {
    module: 'src/components/content/stats/Stats.Tiles',
    exports: [
      { name: 'Tiles', value: Tiles },
    ]
  },
  {
    module: 'src/components/ui/button',
    exports: [
      { name: 'Button', value: Button_84330b1bbe8a1bb4486fd11a1e9edfcb73dcb72a },
    ]
  },
  {
    module: 'src/components/ui/card',
    exports: [
      { name: 'Card', value: Card },
      { name: 'CardContent', value: CardContent },
      { name: 'CardFooter', value: CardFooter },
    ]
  },
  {
    module: 'src/components/ui/badge',
    exports: [
      { name: 'Badge', value: Badge_4993aa9339ae187afc55b9486739db65fa14e5ba },
    ]
  },
  {
    module: 'src/lib/data',
    exports: [
      { name: 'formatPrice', value: formatPrice },
      { name: 'formatDate', value: formatDate },
    ]
  },
  {
    module: 'lib/data',
    exports: [
      { name: 'getFeaturedProducts', value: getFeaturedProducts },
      { name: 'formatDate', value: formatDate_e48efc7333ac73f929d9b272a527b63e4cd08f90 },
      { name: 'getNextUpcomingEvent', value: getNextUpcomingEvent },
    ]
  },
  {
    module: 'src/components/content/products/teaser/_productCard',
    exports: [
      { name: 'ProductCard', value: ProductCard },
    ]
  },
  {
    module: 'src/components/content/products/list/Product.Tiles',
    exports: [
      { name: 'Tiles', value: Tiles_49423b085a70264a020b434efb2a0fbe4b23f2fe },
    ]
  },
  {
    module: 'src/components/ui/input',
    exports: [
      { name: 'Input', value: Input },
    ]
  },
  {
    module: 'lib/iconUtils',
    exports: [
      { name: 'getLucideIcon', value: getLucideIcon },
    ]
  },
  {
    module: 'src/components/content/news/List/News.Grid',
    exports: [
      { name: 'NewsGrid', value: NewsGrid },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client_e836c8c83336161d23b12b70a0f420d5d397b9fe },
    ]
  },
  {
    module: 'src/components/content/news/Teaser/NewsCard',
    exports: [
      { name: 'Default', value: Default },
    ]
  },
  {
    module: 'components/ui/card',
    exports: [
      { name: 'Card', value: Card_ee5df0e436668ea77211f94aa8fc698e82699918 },
      { name: 'CardContent', value: CardContent_ee5df0e436668ea77211f94aa8fc698e82699918 },
    ]
  },
  {
    module: 'src/components/ui/separator',
    exports: [
      { name: 'Separator', value: Separator },
    ]
  },
  {
    module: 'components/ui/ai-generated-badge',
    exports: [
      { name: 'AIGeneratedBadge', value: AIGeneratedBadge },
    ]
  },
  {
    module: 'src/components/content/highlight/teaser/HighlightTeaser',
    exports: [
      { name: 'Default', value: Default_8df8e6cf104460826f9a1215cfab70bad2ccdef2 },
    ]
  },
  {
    module: 'src/components/content/highlight/list/Highlights.Tiles',
    exports: [
      { name: 'Tiles', value: Tiles_2d2f52aec1ad0fb42654646675f88ac474927af0 },
    ]
  },
  {
    module: 'src/components/content/brands/Brands.Slider',
    exports: [
      { name: 'Slider', value: Slider_46091ec46945bf6a641b749ef0b0366a3b6b61c0 },
    ]
  },
  {
    module: 'components/ui/separator',
    exports: [
      { name: 'Separator', value: Separator_fdcdea374acd645ff8e33dd8c598ebe0a6a71fc0 },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
